PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?country ?capital
WHERE {
  ?s rdfs:label ?country ;
     dbo:capital ?capital .
}

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?country (MAX(?population) AS ?maxPopulation)
WHERE {
  ?s rdfs:label ?country ;
     dbo:populationTotal ?population .
}
GROUP BY ?country
ORDER BY DESC(?maxPopulation)
