PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?country ?capital
WHERE {
  ?s rdfs:label ?country ;
     dbo:capital ?capital .
}

//plus cool
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?country ?capital ?pop
WHERE {
  ?s rdfs:label ?country ;
     dbo:capital ?capital ;
  	 dbo:populationTotal ?pop .
}
ORDER BY (?pop)
LIMIT 10

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?country (MAX(?population) AS ?maxPopulation)
WHERE {
  ?s rdfs:label ?country ;
     dbo:populationTotal ?population .
}
GROUP BY ?country
ORDER BY DESC(?maxPopulation)

//cool
PREFIX schema: <http://schema.org/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?country ?area 
WHERE {
  ?s rdfs:label ?country ;
     dbo:areaTotal ?area ;
     schema:growthRate ?gr ;
  	 dbo:populationTotal ?pop .
  FILTER (?gr < 1 && ?area > 300000)
}
ORDER BY (?pop)
LIMIT 10

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?country ?popDensity
WHERE {
  ?s rdfs:label ?country ;
     dbo:populationDensity ?popDensity ;
  FILTER (regex(?country,"^A"))
}
ORDER BY (?popDensity)
LIMIT 10
